repos:
- repo: https://github.com/gitleaks/gitleaks
  rev: 6eaad039603a4de39fddd1cf5f727391efe9974e # v8.30.0
  hooks:
  - id: gitleaks
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 38980559e3a605691d6579f96222c30778e5a69e # 3.0.0
  hooks:
  - id: shellcheck
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # v6.0.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: local
  hooks:
  - id: mypy
    name: mypy
    entry: python lint.py mypy
    language: system
    types: [python]
    pass_filenames: true
    exclude: ^tests/
  - id: ruff
    name: ruff fix
    entry: python lint.py fix
    language: system
    types: [python]
    pass_filenames: true
  - id: ruff
    name: ruff format
    entry: python lint.py format
    language: system
    types: [python]
    pass_filenames: true
  - id: html
    name: djlint
    entry: python lint.py html-fix
    language: system
    types: [html]
    pass_filenames: true
