repos:
- repo: https://github.com/gitleaks/gitleaks
  rev: 83d9cd684c87d95d656c1458ef04895a7f1cbd8e # v8.30.1
  hooks:
  - id: gitleaks
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 38980559e3a605691d6579f96222c30778e5a69e # 3.0.0
  hooks:
  - id: shellcheck
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # v6.0.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/rhysd/actionlint
  rev: 393031adb9afb225ee52ae2ccd7a5af5525e03e8 # v1.7.11
  hooks:
  - id: actionlint
- repo: local
  hooks:
  - id: mypy
    name: mypy
    entry: python lint.py mypy
    language: system
    types: [python]
    pass_filenames: true
    exclude: ^tests/
  - id: ruff-fix
    name: ruff fix
    entry: python lint.py fix
    language: system
    types: [python]
    pass_filenames: true
  - id: ruff-format
    name: ruff format
    entry: python lint.py format
    language: system
    types: [python]
    pass_filenames: true
  - id: html
    name: djlint
    entry: python lint.py html-fix
    language: system
    types: [html]
    pass_filenames: true
