services:
  borgitory:
    build: .
    ports:
      - "8000:8000"   # HTTP port
    volumes:
      # Persistent data storage
      - ./data:/app/data
      # Mount your backup sources (adjust as needed)
      - ./backup-sources:/backup-sources:rw
      # Borg repository storage (where backups are stored)
      - ./borg-repos:/my-repos:rw
    restart: unless-stopped