version: '3.8'

services:
  borgitory:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # Persistent data storage
      - ./data:/app/data
      # Mount your backup sources (adjust as needed)
      - ./backup-sources:/data:ro
      # Borg repository storage (where backups are stored)
      - ./borg-repos:/repos:rw
    environment:
      - SECRET_KEY=your-secret-key-change-in-production
      - DATABASE_URL=sqlite:///./data/borgitory.db
      - DATA_DIR=/app/data
    restart: unless-stopped
    
    # Optional: limit resources
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M