services:
  borgitory:
    build: .
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    ports:
      - "8000:8000"   # HTTP port
    volumes:
      # Persistent data storage
      - ./data:/app/app/data
      # Mount your backup sources (adjust as needed)
      - ./backup-sources:/backup-sources:ro
      # Borg repository storage (where backups are stored)
      - ./borg-repos:/my-repos:rw
