version: '3.8'

services:
  borgitory:
    build: .
    ports:
      - "8443:8443"   # HTTPS port
    volumes:
      # Persistent data storage
      - ./data:/app/data
      # Mount your backup sources (adjust as needed)
      - ./backup-sources:/data:ro
      # Borg repository storage (where backups are stored)
      - ./borg-repos:/repos:rw
    environment:
      - SECRET_KEY=your-secret-key-change-in-production
      # Optional: Add additional hostnames/IPs for SSL certificate
      # - CERT_HOSTS=192.168.1.100,borgitory.local,myserver.home
    restart: unless-stopped
    
    # Optional: limit resources
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M