version: '3.8'

services:
  borgitory:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # Mount Docker socket for container management
      - /var/run/docker.sock:/var/run/docker.sock
      # Persistent data storage
      - ./data:/app/data
      # Mount your backup sources (adjust as needed)
      - ./backup-sources:/data:ro
      # Borg repository storage (where backups are stored)
      - ./borg-repos:/repos:rw
    environment:
      - SECRET_KEY=your-secret-key-change-in-production
      - DATABASE_URL=sqlite:///./data/borgitory.db
      - DATA_DIR=/app/data
      - BORG_DOCKER_IMAGE=ghcr.io/borgmatic-collective/borgmatic:latest
    restart: unless-stopped
    
    # Ensure the borgitory service can access Docker
    user: root
    
    # Optional: limit resources
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M