"""Make passphrase optional

Revision ID: 2628b151e709
Revises: 78c9fff46e06
Create Date: 2025-10-21 08:53:57.131991

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2628b151e709"
down_revision: Union[str, Sequence[str], None] = "78c9fff46e06"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("repositories", schema=None) as batch_op:
        batch_op.alter_column(
            "encrypted_passphrase", existing_type=sa.VARCHAR(), nullable=True
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("repositories", schema=None) as batch_op:
        batch_op.alter_column(
            "encrypted_passphrase", existing_type=sa.VARCHAR(), nullable=False
        )

    # ### end Alembic commands ###
