"""Add compact_after field to PruneConfig

Revision ID: 78c9fff46e06
Revises: d294fdc9a5e7
Create Date: 2025-10-15 09:59:28.501767

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "78c9fff46e06"
down_revision: Union[str, Sequence[str], None] = "d294fdc9a5e7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("prune_configs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("compact_after", sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("prune_configs", schema=None) as batch_op:
        batch_op.drop_column("compact_after")

    # ### end Alembic commands ###
