"""Update job models to use UUID primary keys

Revision ID: fdd026a5ad52
Revises: 18b9095bc772
Create Date: 2025-10-05 10:23:19.044630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdd026a5ad52'
down_revision: Union[str, Sequence[str], None] = '18b9095bc772'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_tasks', schema=None) as batch_op:
        batch_op.alter_column('job_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Uuid(),
               existing_nullable=False)

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(),
               type_=sa.Uuid(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    with op.batch_alter_table('job_tasks', schema=None) as batch_op:
        batch_op.alter_column('job_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    # ### end Alembic commands ###
